# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a42f780b45d004fc9c05a84013f82de29b1ce97071beb258c96a52249197e66181e560425453b1f015db27c71e0319d4db7cae66c4edfbe47a657d1cd02a4f

test:
  secret_key_base: 78fff72b2b8745b3e176eb8fabf307a180598acad5f7b573afcebe8c2cdf6ee7920f577a1a975a51f9cf2bc061ab05d18cd2846b1fb14e0f259fe94ab9255340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
